name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        node:
          - 10.x
          - 12.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npm test
